import { Geist, Geist_Mono } from "next/font/google";
import "@/app/styles/globals.css"
import Navbar from "./components/common/Layout/Navbar";
import Footer from "./components/common/Layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "SIDA",
  icons: {
    icon: "/assets/images/home/svgs/S-icon.svg",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} bg-[#F8FAFC]`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
